POST http://localhost:3001/login
Content-Type: application/json


{
    "email" : "cao.hl.thang@gmail.com",
    "password" : "123"
}


###
POST http://localhost:3001/change-password
Content-Type: application/json


{
    "currentPassword" : "123",
    "password" : "123",
    "confirmedPassword" : "121"
}

###
GET http://localhost:3001/search/vehicle


###
GET http://localhost:3001/login


###
POST http://localhost:3001/register
Content-Type: application/json


{   
    "fullName" : "gaugau",
    "email" : "baquekhatnuoc@gmail.com",
    "password" : "123", 
    "confirmedPassword" : "123"
}



###
POST http://localhost:3001/logout


###
GET http://localhost:3001/user

###
POST http://localhost:3001/forgot-password
Content-Type: application/json


{
    "email" : "cao.hl.thang@gmail.com"
}


###
POST http://localhost:3001/reset-password/5a97ab41d7d07cd5350c27b6723ab5a7b760c8befe5f6e6d0a90c58eb6801f6e
Content-Type: application/json


{
    "password" : "123123"
}


###
GET http://localhost:3001/search-random

###
POST http://localhost:3001/save-flashcard
Content-Type: application/json


{
    "user_id" : 1,
    "word_id" : 1
}

